CREATE TABLE `cadastro` (
  `id` int(11) NOT NULL,
  `varchar1` varchar(255) NULL,
  `varchar2` varchar(255) NULL,
  `varchar3` varchar(255) NULL,
  `varchar4` varchar(255) NULL,
  `varchar5` varchar(255) NULL,
  `num1` int(11) NULL,
  `num2` int(11) NULL,
  `num3` int(11) NULL,
  `num4` int(11) NULL,
  `num5` int(11) NULL,
  `data1` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `bit1` int(1) NULL,
  `bit2` int(1) NULL,
  `bit3` int(1) NULL,
  `bit4` int(1) NULL,
  `bit5` int(1) NULL,
  `texto1` longtext NULL,
  `texto2` longtext NULL,
  `texto3` longtext NULL,
  `texto4` longtext NULL,
  `texto5` longtext NULL,
  `alias` varchar(255) NULL,
  `tabela` varchar(255) CHARACTER SET latin1 NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;